### ISSUE TITLE
Move variables to a common place

### ISSUE THREAD

**Issue by masterpeter2720** [maythamfahmi/itb.corelogger#1]
**Is your feature request related to a problem? Please describe.**
I would suggest moving variables in common place so it become easier to manipulate for example log paths etc.

**Describe the solution you'd like**
Make a json file that contain all variables, or make it possible to pass variables to constructor

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by maythamfahmi** [comment]
@masterpeter2720 working on it, just time allow. thx for feedback.

**Comment by maythamfahmi** [comment]
working on it.
